version: '3.4'

services:
  techchallenge1.api:
    image: ${DOCKER_REGISTRY-}techchallenge1api
    container_name: techchallenge.api
    build:
      context: .
      dockerfile: src/TechChallenge1.API/Dockerfile
    ports:
      - "5000:5000"

    depends_on:
      - techchallenge-database
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  techchallenge-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: techchallenge.database
    ports:
      - "80:80"
      - "1433:1433"
    volumes:
      - ./.containers/db:/var/lib/sqlserver/data
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"