global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'techchallenge1.api'
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:60331']
    tls_config:
      insecure_skip_verify: true
